### ISSUE TITLE
The user_edit_access validation is blocking to run custom hooks and callbacks

### ISSUE THREAD

**Issue by oriolroger** [backdrop-contrib/profile#22]
Hi, we're moving an intranet from Drupal 7 to Backdrop, and we've found that the Profile module is working in a different way. We need to allow some users to edit other users accounts and profiles, and we do that adding custom callbacks to the "user/%/edit" paths.

We've seen that in Backdrop there's already a new callback for these paths, in function profile_menu(), and the access callback function "profile_user_edit_access" starts with a restriction to anybody who can't edit that user.
```
function profile_user_edit_access($account, $type_name) {
  if (!user_edit_access($account)) {
    return FALSE;
  }
  ...
}
```

We wonder if this is strictly necessary, as it's different than it was in Drupal 7 and is not allowing to run other hooks or callbacks to the edit user forms. Or maybe it's something that needs to be validated, and we have to patch it for the specific needs of our project.

Thanks!

**Comment by bugfolder** [comment]
> We wonder if this is strictly necessary...

Well, yes and no. It's necessary because the profile edit pages are being created as sub-tabs of the account edit page, and so if the user doesn't have access to the main account page, there's nowhere to put the sub-tabs. So that user check is necessary.

One could still create the profile edit pages as standalone pages, but then we wouldn't use `MENU_LOCAL_TASK` as the callback type.

If you're allowing "some users to edit other users accounts and profiles," though, then for those users, `user_edit_access($account)` should be returning TRUE, though. So are you granting the permissions to those users to allow them to edit others users' accounts?

At any rate, you could override the current behavior without having to actually patch (change the existing code). Create your own module, use `hook_menu_alter()` to change the `access callback` to your own function that replaces `profile_user_edit_access()`.

**Comment by bugfolder** [comment]
I haven't seen any more on this in over a month. It appears that (a) this is a fairly narrow use case, (b) it is addressed by creating a `hook_menu_alter()` implementation, so I'm closing this. Feel free to reopen and continue the discussion if you feel otherwise.
